// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7yEKUGAzhtBHLmkYgB6D-Y6qOz53wXOo',
    appId: '1:820810705700:web:aba51b7976eb7eacfe21b1',
    messagingSenderId: '820810705700',
    projectId: 'flowerapp-f1a3b',
    authDomain: 'flowerapp-f1a3b.firebaseapp.com',
    storageBucket: 'flowerapp-f1a3b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9kslTZhascIRQvNwBT1CZJdEnVyfHPq0',
    appId: '1:820810705700:android:dff426d80812d4b3fe21b1',
    messagingSenderId: '820810705700',
    projectId: 'flowerapp-f1a3b',
    storageBucket: 'flowerapp-f1a3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyIJ3VTqogZdit6t5pvTExgDo1VsgGWu0',
    appId: '1:820810705700:ios:9df2a42202b52276fe21b1',
    messagingSenderId: '820810705700',
    projectId: 'flowerapp-f1a3b',
    storageBucket: 'flowerapp-f1a3b.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceFlowerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyIJ3VTqogZdit6t5pvTExgDo1VsgGWu0',
    appId: '1:820810705700:ios:9df2a42202b52276fe21b1',
    messagingSenderId: '820810705700',
    projectId: 'flowerapp-f1a3b',
    storageBucket: 'flowerapp-f1a3b.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceFlowerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7yEKUGAzhtBHLmkYgB6D-Y6qOz53wXOo',
    appId: '1:820810705700:web:b00886d44c07a492fe21b1',
    messagingSenderId: '820810705700',
    projectId: 'flowerapp-f1a3b',
    authDomain: 'flowerapp-f1a3b.firebaseapp.com',
    storageBucket: 'flowerapp-f1a3b.firebasestorage.app',
  );
}
